import { z } from 'zod';

export const createExpenseSchema = z.object({
  pondId: z.string().uuid("Valid pond ID required"),
  expenseDate: z.string()
    .min(1, "Expense date is required")
    .refine(val => !isNaN(Date.parse(val)), { message: "Invalid date format" })
    .refine(val => new Date(val) <= new Date(), { message: "Expense date cannot be in the future" }),
  category: z.enum([
    'FINGERLINGS', 'FEED', 'CHEMICALS_LIME', 'EQUIPMENT',
    'LABOR', 'FENCING_INFRASTRUCTURE', 'TRANSPORT', 'MISCELLANEOUS'
  ], { errorMap: () => ({ message: "Select a valid expense category" }) }),
  itemName: z.string().min(2, "Item name is required").max(200).trim(),
  quantity: z.number().positive("Quantity must be positive").optional().nullable(),
  unit: z.string().max(50).optional().nullable().transform(val => val === '' ? null : val),
  unitPrice: z.number().nonnegative("Unit price cannot be negative").optional().nullable(),
  totalAmount: z.number({
    required_error: "Total amount is required",
    invalid_type_error: "Must be a number"
  }).positive("Amount must be positive").max(10000000, "Amount seems too large"),
  paymentMethod: z.enum([
    'CASH', 'UPI', 'BANK_TRANSFER', 'CREDIT', 'OTHER'
  ]).optional().nullable(),
  vendorName: z.string().max(200).optional().nullable().transform(val => val === '' ? null : val),
  receiptNumber: z.string().max(100).optional().nullable().transform(val => val === '' ? null : val),
  notes: z.string().max(500).optional().nullable().transform(val => val === '' ? null : val),
  isAutoGenerated: z.boolean().default(false),
}).refine(data => {
  if (data.quantity && data.unitPrice) {
    const expected = data.quantity * data.unitPrice;
    const variance = Math.abs(expected - data.totalAmount) / expected;
    return variance <= 0.02;
  }
  return true;
}, {
  message: "Total amount does not match quantity × unit price",
  path: ["totalAmount"]
});

export const updateExpenseSchema = createExpenseSchema
  .omit({ pondId: true, isAutoGenerated: true })
  .partial()
  .refine(data => Object.keys(data).length > 0, { message: "At least one field must be provided" });

export const createSaleSchema = z.object({
  pondId: z.string().uuid("Valid pond ID required"),
  saleDate: z.string()
    .min(1, "Sale date is required")
    .refine(val => !isNaN(Date.parse(val)), { message: "Invalid date format" })
    .refine(val => new Date(val) <= new Date(), { message: "Sale date cannot be in the future" }),
  buyerName: z.string().min(2, "Buyer name is required").max(200).trim(),
  buyerPhone: z.string()
    .regex(/^[6-9]\d{9}$/, { message: "Enter valid 10-digit Indian mobile number" })
    .optional().nullable().transform(val => val === '' ? null : val),
  buyerLocation: z.string().max(200).optional().nullable().transform(val => val === '' ? null : val),
  fishQuantityKg: z.number({
    required_error: "Fish quantity is required",
    invalid_type_error: "Must be a number"
  }).positive("Quantity must be positive").max(100000, "Quantity seems too large"),
  pricePerKg: z.number({
    required_error: "Price per kg is required",
    invalid_type_error: "Must be a number"
  }).positive("Price must be positive").max(10000, "Price per kg seems too high"),
  totalAmount: z.number({
    required_error: "Total amount is required",
    invalid_type_error: "Must be a number"
  }).positive("Total must be positive"),
  advanceReceived: z.number().nonnegative("Advance cannot be negative").default(0),
  paymentStatus: z.enum(['PENDING', 'PARTIAL', 'COMPLETED']).default('PENDING'),
  paymentMethod: z.enum([
    'CASH', 'UPI', 'BANK_TRANSFER', 'CREDIT', 'OTHER'
  ]).optional().nullable(),
  transportIncluded: z.boolean().default(false),
  transportCostKg: z.number().nonnegative().optional().nullable(),
  notes: z.string().max(500).optional().nullable().transform(val => val === '' ? null : val),
}).refine(data => {
  const expected = data.fishQuantityKg * data.pricePerKg;
  const variance = Math.abs(expected - data.totalAmount) / expected;
  return variance <= 0.02;
}, {
  message: "Total amount does not match quantity × price per kg",
  path: ["totalAmount"]
}).refine(data => {
  return data.advanceReceived <= data.totalAmount;
}, {
  message: "Advance cannot exceed total amount",
  path: ["advanceReceived"]
});

export const updateSaleSchema = createSaleSchema
  .omit({ pondId: true })
  .partial()
  .refine(data => Object.keys(data).length > 0, { message: "At least one field must be provided" });

export const recordPaymentSchema = z.object({
  amountReceived: z.number({
    required_error: "Amount is required",
    invalid_type_error: "Must be a number"
  }).positive("Amount must be positive"),
  paymentDate: z.string()
    .min(1, "Payment date required")
    .refine(val => !isNaN(Date.parse(val))),
  paymentMethod: z.enum([
    'CASH', 'UPI', 'BANK_TRANSFER', 'CREDIT', 'OTHER'
  ]),
  notes: z.string().max(500).optional(),
});

export const createMarketPriceSchema = z.object({
  pondId: z.string().uuid("Valid pond ID required"),
  priceDate: z.string()
    .min(1, "Date required")
    .refine(val => !isNaN(Date.parse(val))),
  species: z.string().min(2, "Species required").max(100).trim(),
  pricePerKg: z.number({
    required_error: "Price per kg required",
    invalid_type_error: "Must be a number"
  }).positive("Price must be positive").max(10000),
  marketLocation: z.string().max(200).optional().nullable().transform(val => val === '' ? null : val),
  priceType: z.enum(['FARM_GATE', 'WHOLESALE', 'RETAIL']).default('FARM_GATE'),
  notes: z.string().max(500).optional().nullable().transform(val => val === '' ? null : val),
});

export const setBudgetSchema = z.object({
  pondId: z.string().uuid(),
  monthYear: z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/, { message: "Format must be YYYY-MM" }),
  budgetAmount: z.number().positive("Budget must be positive").max(10000000),
  category: z.enum([
    'FINGERLINGS', 'FEED', 'CHEMICALS_LIME',
    'EQUIPMENT', 'LABOR', 'FENCING_INFRASTRUCTURE',
    'TRANSPORT', 'MISCELLANEOUS', 'TOTAL'
  ]),
});

export const financialQuerySchema = z.object({
  pondId: z.string().uuid(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  category: z.string().optional(),
  paymentStatus: z.string().optional(),
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
});

export const financialStatsQuerySchema = z.object({
  pondId: z.string().uuid(),
  period: z.enum(['current_month', '3months', '6months', 'year', 'all']).default('current_month'),
});

export type CreateExpenseDTO = z.infer<typeof createExpenseSchema>;
export type UpdateExpenseDTO = z.infer<typeof updateExpenseSchema>;
export type CreateSaleDTO = z.infer<typeof createSaleSchema>;
export type UpdateSaleDTO = z.infer<typeof updateSaleSchema>;
export type RecordPaymentDTO = z.infer<typeof recordPaymentSchema>;
export type CreateMarketPriceDTO = z.infer<typeof createMarketPriceSchema>;
export type SetBudgetDTO = z.infer<typeof setBudgetSchema>;
export type FinancialQuery = z.infer<typeof financialQuerySchema>;
export type FinancialStatsQuery = z.infer<typeof financialStatsQuerySchema>;
