import React, { useState, useEffect } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Expense, ExpenseCategory, PaymentMethod } from '../../types/financials.types';
import { EXPENSE_CATEGORY_CONFIG, PAYMENT_METHOD_CONFIG } from '../../utils/constants';

const expenseSchema = z.object({
  expenseDate: z.string().min(1, "Date is required"),
  category: z.string().min(1, "Category is required"),
  itemName: z.string().min(2, "Item name required").max(200),
  quantity: z.number().positive().optional().or(z.literal('')),
  unit: z.string().optional(),
  unitPrice: z.number().nonnegative().optional().or(z.literal('')),
  totalAmount: z.number({ required_error: "Total amount required" }).positive(),
  paymentMethod: z.string().optional(),
  vendorName: z.string().optional(),
  receiptNumber: z.string().optional(),
  notes: z.string().optional(),
});

type ExpenseFormData = z.infer<typeof expenseSchema>;

interface ExpenseFormProps {
  initialData?: Expense | null;
  onSubmit: (data: any) => Promise<void>;
  onCancel: () => void;
  isLoading: boolean;
}

export const ExpenseForm: React.FC<ExpenseFormProps> = ({ initialData, onSubmit, onCancel, isLoading }) => {
  const [autoCalc, setAutoCalc] = useState(true);

  const { register, handleSubmit, control, watch, setValue, formState: { errors } } = useForm<ExpenseFormData>({
    resolver: zodResolver(expenseSchema),
    defaultValues: {
      expenseDate: initialData?.expenseDate ? new Date(initialData.expenseDate).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
      category: initialData?.category || '',
      itemName: initialData?.itemName || '',
      quantity: initialData?.quantity || '',
      unit: initialData?.unit || '',
      unitPrice: initialData?.unitPrice || '',
      totalAmount: initialData?.totalAmount || '' as any,
      paymentMethod: initialData?.paymentMethod || '',
      vendorName: initialData?.vendorName || '',
      receiptNumber: initialData?.receiptNumber || '',
      notes: initialData?.notes || '',
    }
  });

  const qty = watch('quantity');
  const price = watch('unitPrice');

  useEffect(() => {
    if (autoCalc && qty && price && typeof qty === 'number' && typeof price === 'number') {
      setValue('totalAmount', Number((qty * price).toFixed(2)));
    }
  }, [qty, price, autoCalc, setValue]);

  const categories = Object.keys(EXPENSE_CATEGORY_CONFIG) as ExpenseCategory[];
  const paymentMethods = Object.keys(PAYMENT_METHOD_CONFIG) as PaymentMethod[];

  const isAuto = initialData?.isAutoGenerated;

  const handleFormSubmit = (data: ExpenseFormData) => {
    const cleanData = { ...data };
    
    // Sanitize optional numeric fields if they are empty strings
    if (cleanData.quantity === '' as any) delete cleanData.quantity;
    if (cleanData.unitPrice === '' as any) delete cleanData.unitPrice;
    
    onSubmit(cleanData);
  };

  return (
    <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-6">
      {isAuto && (
        <div className="bg-blue-900/20 text-blue-400 p-4 rounded-lg flex items-start gap-3">
          <span className="text-xl">ℹ️</span>
          <div>
            <h4 className="font-semibold">Auto-Generated Record</h4>
            <p className="text-sm">This expense was generated automatically from {initialData.sourceModule}. Some fields cannot be edited directly.</p>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1">Date *</label>
          <input 
            type="date" 
            {...register('expenseDate')}
            disabled={isAuto}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500 disabled:bg-slate-800/50 disabled:text-slate-500" 
          />
          {errors.expenseDate && <p className="text-red-500 text-xs mt-1">{errors.expenseDate.message}</p>}
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1">Category *</label>
          <select 
            {...register('category')}
            disabled={isAuto}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500 disabled:bg-slate-800/50 disabled:text-slate-500"
          >
            <option value="">Select Category</option>
            {categories.map(cat => (
              <option key={cat} value={cat}>
                {EXPENSE_CATEGORY_CONFIG[cat as keyof typeof EXPENSE_CATEGORY_CONFIG].emoji} {EXPENSE_CATEGORY_CONFIG[cat as keyof typeof EXPENSE_CATEGORY_CONFIG].label}
              </option>
            ))}
          </select>
          {errors.category && <p className="text-red-500 text-xs mt-1">{errors.category.message}</p>}
        </div>

        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-300 mb-1">Item Description *</label>
          <input 
            type="text" 
            placeholder="What was purchased?"
            {...register('itemName')}
            disabled={isAuto}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500 disabled:bg-slate-800/50 disabled:text-slate-500" 
          />
          {errors.itemName && <p className="text-red-500 text-xs mt-1">{errors.itemName.message}</p>}
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1">Quantity</label>
          <input 
            type="number" 
            step="0.01"
            placeholder="e.g. 50"
            {...register('quantity', { valueAsNumber: true })}
            disabled={isAuto}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500 disabled:bg-slate-800/50 disabled:text-slate-500" 
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1">Unit</label>
          <input 
            type="text" 
            placeholder="e.g. kg, pieces, liters"
            {...register('unit')}
            disabled={isAuto}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500 disabled:bg-slate-800/50 disabled:text-slate-500" 
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1">Unit Price (₹)</label>
          <input 
            type="number" 
            step="0.01"
            {...register('unitPrice', { valueAsNumber: true })}
            disabled={isAuto}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500 disabled:bg-slate-800/50 disabled:text-slate-500" 
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1 flex justify-between">
            <span>Total Amount (₹) *</span>
            <span className="text-xs text-sky-400 cursor-pointer" onClick={() => setAutoCalc(!autoCalc)}>
              {autoCalc ? 'Auto-calculating' : 'Manual entry'}
            </span>
          </label>
          <input 
            type="number" 
            step="0.01"
            {...register('totalAmount', { valueAsNumber: true })}
            disabled={isAuto || (autoCalc && !!qty && !!price)}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500 disabled:bg-slate-800/50 disabled:text-slate-500 font-bold" 
          />
          {errors.totalAmount && <p className="text-red-500 text-xs mt-1">{errors.totalAmount.message}</p>}
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1">Vendor/Supplier Name</label>
          <input 
            type="text" 
            {...register('vendorName')}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500" 
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1">Receipt/Bill Number</label>
          <input 
            type="text" 
            {...register('receiptNumber')}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500" 
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-300 mb-1">Payment Method</label>
          <select 
            {...register('paymentMethod')}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500"
          >
            <option value="">Select Method</option>
            {paymentMethods.map(pm => (
              <option key={pm} value={pm}>
                {PAYMENT_METHOD_CONFIG[pm].icon} {PAYMENT_METHOD_CONFIG[pm].label}
              </option>
            ))}
          </select>
        </div>
        
        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-300 mb-1">Additional Notes</label>
          <textarea 
            {...register('notes')}
            rows={2}
            className="w-full rounded-lg bg-slate-800 border-slate-700 text-white shadow-sm focus:border-sky-500 focus:ring-sky-500" 
          />
        </div>
      </div>

      <div className="flex justify-end gap-3 pt-4 border-t border-slate-800">
        <button
          type="button"
          onClick={onCancel}
          disabled={isLoading}
          className="px-4 py-2 text-slate-400 font-medium hover:bg-slate-800 hover:text-white rounded-lg transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={isLoading}
          className="px-4 py-2 bg-sky-600 text-white font-medium rounded-lg hover:bg-sky-500 transition-colors disabled:opacity-50"
        >
          {isLoading ? 'Saving...' : initialData ? 'Update Expense' : 'Save Expense'}
        </button>
      </div>
    </form>
  );
};
