export type ExpenseCategory = 
  | 'FINGERLINGS' 
  | 'FEED' 
  | 'CHEMICALS_LIME' 
  | 'EQUIPMENT' 
  | 'LABOR' 
  | 'FENCING_INFRASTRUCTURE' 
  | 'TRANSPORT' 
  | 'MISCELLANEOUS'
  | 'TOTAL';

export type PaymentMethod = 'CASH' | 'UPI' | 'BANK_TRANSFER' | 'CREDIT' | 'OTHER';
export type PaymentStatus = 'PENDING' | 'PARTIAL' | 'COMPLETED';
export type PriceType = 'FARM_GATE' | 'WHOLESALE' | 'RETAIL';

export interface Expense {
  id: string;
  pondId: string;
  expenseDate: string;
  category: ExpenseCategory;
  itemName: string;
  quantity: number | null;
  unit: string | null;
  unitPrice: number | null;
  totalAmount: number;
  paymentMethod: PaymentMethod | null;
  vendorName: string | null;
  receiptNumber: string | null;
  isAutoGenerated: boolean;
  sourceModule: string | null;
  sourceRecordId: string | null;
  notes: string | null;
  receiptPhotoUrl: string | null;
}

export interface Sale {
  id: string;
  pondId: string;
  saleDate: string;
  buyerName: string;
  buyerPhone: string | null;
  buyerLocation: string | null;
  fishQuantityKg: number;
  pricePerKg: number;
  totalAmount: number;
  advanceReceived: number;
  balancePending: number;
  paymentStatus: PaymentStatus;
  paymentMethod: PaymentMethod | null;
  transportIncluded: boolean;
  transportCostKg: number | null;
  invoiceNumber: string | null;
  notes: string | null;
}

export interface MarketPrice {
  id: string;
  pondId: string;
  priceDate: string;
  species: string;
  pricePerKg: number;
  marketLocation: string | null;
  priceType: PriceType;
  notes: string | null;
}

export interface Budget {
  id: string;
  pondId: string;
  monthYear: string;
  category: ExpenseCategory;
  budgetAmount: number;
}

export interface CategoryBreakdown {
  category: ExpenseCategory;
  label: string;
  total: number;
  count: number;
  percentage: number;
}

export interface MonthlyExpense {
  month: string;
  displayMonth: string;
  total: number;
  byCategory: Partial<Record<ExpenseCategory, number>>;
}

export interface MonthlySale {
  month: string;
  displayMonth: string;
  totalRevenue: number;
  totalKg: number;
  avgPricePerKg: number;
  saleCount: number;
}

export interface MonthlyCashFlow {
  month: string;
  displayMonth: string;
  expenses: number;
  revenue: number;
  netCashFlow: number;
  cumulativeCashFlow: number;
}

export interface BudgetVsActual {
  category: string;
  label: string;
  budgeted: number;
  actual: number;
  variance: number;
  variancePercent: number;
  status: 'under' | 'over' | 'no_budget';
}

export interface BreakEvenAnalysis {
  breakEvenRevenue: number;
  breakEvenKg: number | null;
  currentRevenue: number;
  revenueToBreakEven: number;
  percentageToBreakEven: number;
  isBreakEvenReached: boolean;
  estimatedBreakEvenDate: string | null;
}

export interface HarvestProjection {
  estimatedAlive: number;
  currentAvgWeightGrams: number;
  targetHarvestWeightGrams: number;
  estimatedHarvestKg: number;
  latestMarketPricePerKg: number;
  projectedRevenue: number;
  projectedProfit: number;
  projectedROI: number;
  totalInvestedSoFar: number;
  remainingInvestmentNeeded?: number;
}

export interface PLStatement {
  period: string;
  totalIncome: number;
  totalExpenses: number;
  grossProfit: number;
  netProfit: number;
  profitMargin: number;
  isProfitable: boolean;
  incomeBySource: {
    fishSales: number;
    otherIncome: number;
  };
  expensesByCategory: CategoryBreakdown[];
}

export interface FinancialStats {
  period: string;
  periodDays: number;
  totalExpenses: number;
  totalRevenue: number;
  netProfitLoss: number;
  isProfitable: boolean;
  currentMonthExpenses: number;
  currentMonthRevenue: number;
  totalFishSoldKg: number;
  costPerKgProduced: number | null;
  avgSalePricePerKg: number | null;
  totalPendingAmount: number;
  pendingSalesCount: number;
  expensesByCategory: CategoryBreakdown[];
  monthlyExpenses: MonthlyExpense[];
  monthlySales: MonthlySale[];
  cashFlow: MonthlyCashFlow[];
  budgetVsActual: BudgetVsActual[];
  breakEven: BreakEvenAnalysis;
  harvestProjection: HarvestProjection | null;
  plStatement: PLStatement;
  marketPrices: MarketPrice[];
}

export interface FinancialOverview {
  stats: FinancialStats;
  recentExpenses: Expense[];
  recentSales: Sale[];
}
